version: 0.0
os: linux
files:
  - source: /
    destination: /etc/company/public_index_api/

hooks:
  BeforeInstall:
    - location: /scripts/before-install.sh
      runas: root
      timeout: 300
  AfterInstall:
    - location: /scripts/install-deps.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: /scripts/start_server.sh
      runas: root
      timeout: 300